const calendar=document.getElementById("calendar"),monthTitle=document.getElementById("monthTitle"),modal=document.getElementById("modal"),form=document.getElementById("scheduleForm"),dateInput=document.getElementById("dateInput"),titleInput=document.getElementById("titleInput"),timeInput=document.getElementById("timeInput"),memoInput=document.getElementById("memoInput"),imageInput=document.getElementById("imageInput"),imagePreviewWrap=document.getElementById("imagePreviewWrap"),imagePreview=document.getElementById("imagePreview"),removeImageBtn=document.getElementById("removeImageBtn"),modalTitle=document.getElementById("modalTitle"),deleteBtn=document.getElementById("deleteBtn"),imageViewer=document.getElementById("imageViewer"),imageViewerImg=document.getElementById("imageViewerImg");
let currentDate=new Date(),editingId=null,currentImageData="";const STORAGE_KEY="toss_style_scheduler_events_v3";
function loadEvents(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}function saveEvents(events){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(events))}catch(e){alert("저장 공간이 부족합니다. 이미지 크기를 줄이거나 기존 일정을 삭제해주세요.");throw e}}function pad(n){return String(n).padStart(2,"0")}function dateKey(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function resetImagePreview(){currentImageData="";imageInput.value="";imagePreview.src="";imagePreviewWrap.classList.add("hidden")}function showImagePreview(src){currentImageData=src||"";if(!src)return resetImagePreview();imagePreview.src=src;imagePreviewWrap.classList.remove("hidden")}
function compressImage(file,maxSize=1400,quality=.82){return new Promise((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject(new Error("이미지 파일이 아닙니다."));const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight;if(Math.max(w,h)>maxSize){const s=maxSize/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);resolve(c.toDataURL("image/jpeg",quality))};img.onerror=()=>reject(new Error("이미지를 읽을 수 없습니다."));img.src=r.result};r.onerror=()=>reject(new Error("파일을 읽을 수 없습니다."));r.readAsDataURL(file)})}
function renderCalendar(){const year=currentDate.getFullYear(),month=currentDate.getMonth();monthTitle.textContent=`${year}년 ${month+1}월`;calendar.innerHTML="";const firstDay=new Date(year,month,1).getDay(),lastDate=new Date(year,month+1,0).getDate(),prevLastDate=new Date(year,month,0).getDate(),totalCells=Math.ceil((firstDay+lastDate)/7)*7,events=loadEvents();for(let i=0;i<totalCells;i++){const cell=document.createElement("div");cell.className="day";let cellDate,dayNumber;if(i<firstDay){dayNumber=prevLastDate-firstDay+i+1;cellDate=new Date(year,month-1,dayNumber);cell.classList.add("other-month")}else if(i>=firstDay+lastDate){dayNumber=i-firstDay-lastDate+1;cellDate=new Date(year,month+1,dayNumber);cell.classList.add("other-month")}else{dayNumber=i-firstDay+1;cellDate=new Date(year,month,dayNumber)}const key=dateKey(cellDate);if(key===dateKey(new Date()))cell.classList.add("today");const number=document.createElement("div");number.className="day-number";number.textContent=dayNumber;cell.appendChild(number);const list=document.createElement("div");list.className="event-list";events.filter(e=>e.date===key).sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99")).forEach(event=>{const item=document.createElement("div");item.className="event";item.title=event.memo||event.title;if(event.time){const t=document.createElement("span");t.className="event-time";t.textContent=event.time;item.appendChild(t)}if(event.image){const m=document.createElement("span");m.className="image-mark";m.textContent="📷";item.appendChild(m)}item.appendChild(document.createTextNode(event.title));item.addEventListener("click",e=>{e.stopPropagation();openEdit(event.id)});list.appendChild(item)});cell.appendChild(list);cell.addEventListener("click",()=>openAdd(key));calendar.appendChild(cell)}}
function openAdd(date=dateKey(new Date())){editingId=null;modalTitle.textContent="일정 추가";form.reset();dateInput.value=date;timeInput.value="";timeInput.removeAttribute("readonly");timeInput.disabled=false;resetImagePreview();deleteBtn.classList.add("hidden");modal.classList.remove("hidden");titleInput.focus()}
function openEdit(id){const event=loadEvents().find(e=>e.id===id);if(!event)return;editingId=id;modalTitle.textContent="일정 수정";dateInput.value=event.date;titleInput.value=event.title;timeInput.value=event.time||"";timeInput.removeAttribute("readonly");timeInput.disabled=false;memoInput.value=event.memo||"";event.image?showImagePreview(event.image):resetImagePreview();deleteBtn.classList.remove("hidden");modal.classList.remove("hidden");titleInput.focus()}
function closeModal(){modal.classList.add("hidden");editingId=null;form.reset();resetImagePreview()}
form.addEventListener("submit",e=>{e.preventDefault();const events=loadEvents(),timeValue=timeInput.value.trim(),validTime=timeValue===""||/^([01]\d|2[0-3]):[0-5]\d$/.test(timeValue);if(!validTime){alert("시간은 00:00 ~ 23:59 형식으로 입력해주세요.");timeInput.focus();return}const data={id:editingId||(crypto?.randomUUID?crypto.randomUUID():String(Date.now())),date:dateInput.value,title:titleInput.value.trim(),time:timeValue,memo:memoInput.value.trim(),image:currentImageData};if(!data.title)return alert("일정 제목을 입력해주세요.");if(!data.date)return alert("날짜를 선택해주세요.");if(editingId){const i=events.findIndex(e=>e.id===editingId);if(i!==-1)events[i]=data}else events.push(data);try{saveEvents(events)}catch{return}closeModal();renderCalendar()});
imageInput.addEventListener("change",async()=>{const file=imageInput.files?.[0];if(!file)return;if(file.size>10*1024*1024){alert("원본 이미지가 너무 큽니다. 10MB 이하의 이미지를 선택해주세요.");imageInput.value="";return}try{showImagePreview(await compressImage(file))}catch(e){alert("이미지를 불러오지 못했습니다.");console.error(e)}});removeImageBtn.addEventListener("click",resetImagePreview);
deleteBtn.addEventListener("click",()=>{if(!editingId)return;if(!confirm("이 일정을 삭제하시겠습니까?"))return;saveEvents(loadEvents().filter(e=>e.id!==editingId));closeModal();renderCalendar()});
document.getElementById("prevBtn").addEventListener("click",()=>{currentDate=new Date(currentDate.getFullYear(),currentDate.getMonth()-1,1);renderCalendar()});document.getElementById("nextBtn").addEventListener("click",()=>{currentDate=new Date(currentDate.getFullYear(),currentDate.getMonth()+1,1);renderCalendar()});document.getElementById("todayBtn").addEventListener("click",()=>{currentDate=new Date();renderCalendar()});document.getElementById("addBtn").addEventListener("click",()=>openAdd());document.getElementById("closeBtn").addEventListener("click",closeModal);document.getElementById("cancelBtn").addEventListener("click",closeModal);document.querySelector(".modal-backdrop").addEventListener("click",closeModal);
function closeImageViewer(){imageViewer.classList.add("hidden");imageViewerImg.src=""}document.getElementById("imageViewerClose").addEventListener("click",closeImageViewer);document.querySelector(".image-viewer-backdrop").addEventListener("click",closeImageViewer);renderCalendar();
